name: npm
on:
  push:
    branches: ["**"]
  release:
    types: [published]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}

      - uses: actions/checkout@v4

      - run: npm ci

      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}

      - uses: actions/checkout@v4

      - run: npm ci

      - run: npm test

  pack:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}

      - uses: actions/checkout@v4

      - run: npm ci

      - run: npm run build

      - run: npm pack

      - id: pack
        run: echo package=$(basename $(npm pack) .tgz) >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{steps.pack.outputs.package}}
          path: "*.tgz"

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'release'
    needs:
      - lint
      - test
      - pack
    environment: npm
    steps:

      - uses: actions/setup-node@v4
        with:
          node-version: ${{vars.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/

      - uses: actions/download-artifact@v4

      - env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        run: npm publish --provenance --access public $(find -type f -name '*.tgz')
